name: mkopo_wetu
description: "Mkopo Wetu"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^16.2.4
  google_fonts: ^6.3.1
  provider: ^6.1.5+1
  http: ^1.5.0
  connectivity_plus: ^7.0.0
  google_mobile_ads: ^6.0.0
  flutter_svg: ^2.0.9
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  lottie: ^3.1.2
  firebase_database: ^12.0.2
  intl: ^0.20.2
  pinput: ^5.0.2
  shared_preferences: ^2.5.3
  introduction_screen: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
