// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC42t6FUfYSbsNOpVbxdYViA04dtUrkT78',
    appId: '1:363494444667:web:1cd58c88c3d0ef92a21cde',
    messagingSenderId: '363494444667',
    projectId: 'mkopo-wetu',
    authDomain: 'mkopo-wetu.firebaseapp.com',
    databaseURL: 'https://mkopo-wetu-default-rtdb.firebaseio.com',
    storageBucket: 'mkopo-wetu.firebasestorage.app',
    measurementId: 'G-QJDBBE3EZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSkPJ0R3CjTwECZRltMvAD8f4vVsr2N_w',
    appId: '1:363494444667:android:4356f9e0eb521335a21cde',
    messagingSenderId: '363494444667',
    projectId: 'mkopo-wetu',
    databaseURL: 'https://mkopo-wetu-default-rtdb.firebaseio.com',
    storageBucket: 'mkopo-wetu.firebasestorage.app',
  );

}