// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI_17L3ql3pz61TBbiN0RlcuTSSXCv_VM',
    appId: '1:508486369644:web:e0eb2cb08b0701b229b349',
    messagingSenderId: '508486369644',
    projectId: 'okoa-loan-694e3',
    authDomain: 'okoa-loan-694e3.firebaseapp.com',
    storageBucket: 'okoa-loan-694e3.firebasestorage.app',
    measurementId: 'G-9W0CKF12ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA7TpO0GKgzq6nSZZP_sOyiCdEKxgNlh4',
    appId: '1:508486369644:android:1c9a85c41df2c60129b349',
    messagingSenderId: '508486369644',
    projectId: 'okoa-loan-694e3',
    storageBucket: 'okoa-loan-694e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQPi_YnkywyJdfWiIOeN7UN3-QrKXX_LU',
    appId: '1:508486369644:ios:c38c5c4663e16ff629b349',
    messagingSenderId: '508486369644',
    projectId: 'okoa-loan-694e3',
    storageBucket: 'okoa-loan-694e3.firebasestorage.app',
    iosBundleId: 'com.okoaloan.ke',
  );
}
